language: rust
before_install:
  - yes | sudo apt-add-repository ppa:sonkun/sfml-development
  - sudo apt-get update
install:
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libcsfml-dev
