[package]

name = "rustchip"
version = "0.1.0"
authors = ["Derek Guenther <dguenther9@gmail.com>"]

[dependencies]
log = "0.3.1"
rand = "0.3.7"

[dependencies.rust-sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
